[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/api/videos/*"
  to = "/.netlify/functions/videos/:splat"
  status = 200

[[redirects]]
  from = "/api/categories/*"
  to = "/.netlify/functions/videos/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
