[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/save-data"
  to = "/.netlify/functions/save-data"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
